//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donated
    {
        public int donateId { get; set; }
        public Nullable<int> donationEventId { get; set; }
        public Nullable<int> userId { get; set; }
        public string donationType { get; set; }
        public string donationUnit { get; set; }
        public Nullable<decimal> donationQuantity { get; set; }
        public Nullable<int> status { get; set; }
        public string referenceNum { get; set; }
        public Nullable<System.DateTime> donatedAt { get; set; }
    
        public virtual DonationEvent DonationEvent { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
