//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabang_Hub
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationEvent
    {
        public int donationEventId { get; set; }
        public Nullable<int> userId { get; set; }
        public string donationEventName { get; set; }
        public string donationDescription { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public string location { get; set; }
        public Nullable<int> status { get; set; }
    }
}
