
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class RequestSkill
{

    public int requestSkillId { get; set; }

    public string requestSkillName { get; set; }

    public string requestSkillImage { get; set; }

    public string orgName { get; set; }

}

}
