
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Tabang_Hub
{

using System;
    using System.Collections.Generic;
    
public partial class vw_AllVolunteers
{

    public Nullable<int> userId { get; set; }

    public string FullName { get; set; }

    public Nullable<decimal> OverallRating { get; set; }

    public string Feedback { get; set; }

    public string availability { get; set; }

}

}
