runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app -t 60

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "3.11"

resources:
  memory_gb: 4
  disk_size_gb: 20
  cpu: 2

manual_scaling:
  instances: 1